### ISSUE TITLE
amxmodx plugin doesnt compile

### ISSUE THREAD

**Issue by fred0r** [musosoft/hlstatsx-community-edition#1]
**Describe the bug**
when trying to compile the amxmodx-plugin  with `amxmodx 1.10 - build 5467`:
`hlstatsx_commands_cstrike.sma(926) : error 032: array index out of bounds (variable "color3")`

**To Reproduce**
1. Go to https://www.amxmodx.org/downloads-new.php?branch=master
2. Click and install https://www.amxmodx.org/amxxdrop/1.10/amxmodx-1.10.0-git5467-base-linux.tar.gz / https://www.amxmodx.org/amxxdrop/1.10/amxmodx-1.10.0-git5467-cstrike-linux.tar.gz
3. Compile https://raw.githubusercontent.com/musosoft/hlstatsx-community-edition/refs/heads/master/src/amxmodx/scripting/hlstatsx_commands_cstrike.sma

**Expected behavior**
No Error and a hlstatsx_commands_cstrike amxx

**Additional context**
Maybe try to compare to https://raw.githubusercontent.com/gamemedev/plugin-amxmodx/refs/heads/master/scripting/gameme_cstrike.sma - this compiles fine.

**Comment by musosoft** [comment]
Thanks for reporting,

Fixed, please try.

https://github.com/musosoft/hlstatsx-community-edition/commit/ebaba05c4ab75c0ae48879092a24482390e4ecab
